#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer; do
    echo "› ${installer}"
    sh -c "${installer}"
done

# Run Homebrew through the Brewfile
if test "$(uname)" = "Darwin"; then
    echo "› brew bundle"
    # brew bundle
    $DOTFILES/homebrew/my_brew_bundle
fi
